# Generated by Django 3.1.7 on 2021-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(help_text='Squirrel Identifier', max_length=255, primary_key=True, serialize=False, verbose_name='Unique Squirrel ID')),
                ('x', models.FloatField(help_text='Geo Latitude', verbose_name='Latitude')),
                ('y', models.FloatField(help_text='Geo Longitude', verbose_name='Longitude')),
                ('hectare', models.CharField(help_text='Park Hectare Identifier', max_length=255, verbose_name='Hectare')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, verbose_name='Shift')),
                ('date', models.DateField(verbose_name='Date')),
                ('hectare_squirrel_number', models.IntegerField(verbose_name='Hectare Squirrel Number')),
                ('age', models.CharField(max_length=255, verbose_name='Age')),
                ('primary_fur_color', models.CharField(max_length=255, verbose_name='Primary Fur Color')),
                ('highlight_fur_color', models.CharField(max_length=255, verbose_name='Highlight Fur Color')),
                ('combination_of_primary_and_highlight_color', models.CharField(max_length=255, verbose_name='Combination of Primary and Highlight Color')),
                ('color_notes', models.CharField(max_length=255, verbose_name='Color notes')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('above_ground_sighter_measurement', models.CharField(max_length=255, verbose_name='Above Ground Sighter Measurement')),
                ('specific_location', models.CharField(max_length=255, verbose_name='Specific Location')),
                ('running', models.BooleanField(verbose_name='Running')),
                ('chasing', models.BooleanField(verbose_name='Chasing')),
                ('climbing', models.BooleanField(verbose_name='Climbing')),
                ('eating', models.BooleanField(verbose_name='Eating')),
                ('foraging', models.BooleanField(verbose_name='Foraging')),
                ('other_activities', models.CharField(max_length=255, verbose_name='Other Activities')),
                ('kuks', models.BooleanField(verbose_name='Kuks')),
                ('quaas', models.BooleanField(verbose_name='Quaas')),
                ('moans', models.BooleanField(verbose_name='Moans')),
                ('tail_flags', models.BooleanField(verbose_name='Tail flags')),
                ('tail_twitches', models.BooleanField(verbose_name='Tail twitches')),
                ('approaches', models.BooleanField(verbose_name='Approaches')),
                ('indifferent', models.BooleanField(verbose_name='Indifferent')),
                ('runs_from', models.BooleanField(verbose_name='Runs from')),
                ('other_interactions', models.CharField(max_length=255, verbose_name='Other Interactions')),
            ],
        ),
    ]
