# Generated by Django 3.1.7 on 2021-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker_app', '0002_auto_20210306_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='above_ground_sighter_measurement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Above Ground Sighter Measurement'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, max_length=255, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='color_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Color notes'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='combination_of_primary_and_highlight_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Combination of Primary and Highlight Color'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='highlight_fur_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Highlight Fur Color'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_interactions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Interactions'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primary Fur Color'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Specific Location'),
        ),
    ]
