# Generated by Django 3.1.7 on 2021-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker_app', '0004_auto_20210306_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='x',
            field=models.FloatField(help_text='Geo Latitude', verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='y',
            field=models.FloatField(help_text='Geo Longitude', verbose_name='Y'),
        ),
    ]
