# Generated by Django 3.1.7 on 2021-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker_app', '0005_auto_20210306_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='lat_long',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lat/Long'),
        ),
    ]
