# Generated by Django 3.1.7 on 2021-04-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_tracker_app', '0006_squirrel_lat_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='hectare_squirrel_number',
            field=models.IntegerField(blank=True, verbose_name='Hectare Squirrel Number'),
        ),
    ]
